name: Cocoapods

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: "12.4"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods StorybookKit
        run: pod lib lint StorybookKit.podspec
      - name: Lint Cocoapods StorybookUI
        run: pod lib lint --include-podspecs=StorybookKit.podspec StorybookUI.podspec
